
print('Escolha dois numeros e veja sua media aritimetica!')
print('~'*20)
x=int(input('digite um numero: '))
y=int(input('digite um numero: '))
print('~'*20)
z=((x + y)/2)
print('A media é: {}'.format(z))
print('~'*20)
print('Escolha dois numeros e veja sua media aritimetica!')

print('~'*20)
j=int(input('digite um numero: '))
u=int(input('digite um numero: '))
print('~'*20)
r=((j + u)/2)
print('A media é: {}'.format(r))

print('~'*20)
print('Escolha dois numeros e veja sua media aritimetica!')
print('~'*20)
e=int(input('digite um numero: '))
t=int(input('digite um numero: '))
print('~'*20)
o=((e + t)/2)
print('A media é: {}'.format(o))
print('~'*20)
print('as medias sao: \n {0} \n {1} \n {2} '.format(z,r,o))